name: "Hello Actions"

description: "Greet someone"

author: " Yosati "



inputs:

  MY_NAME:Yosati

    description: "Who to greet"

    required: true

    default: "World"



runs:

  using: "docker"

  image: "Dockerfile"



branding:

  icon: "mic"

  color: "green"
